export const orderActionTypes = {
  GET_ALL_ACTIVE_ORDERS_FOR_ADMIN: "GET_ALL_ACTIVE_ORDERS_FOR_ADMIN",
  GET_ALL_ACTIVE_ORDERS_FOR_USER: "GET_ALL_ACTIVE_ORDERS_FOR_USER",
  GET_ALL_COMPLETED_ORDERS_FOR_ADMIN: "GET_ALL_COMPLETED_ORDERS_FOR_ADMIN",
  GET_ALL_COMPLETED_ORDERS_FOR_USER: "GET_ALL_COMPLETED_ORDERS_FOR_USER",
  CLEAR_ORDERS: "CLEAR_ORDERS",
};
